apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
  #encrypted: yes
  #kmsKeyId: arn:aws:kms:eu-west-3:080266302756:key/4465d43b-fd5d-4be1-807e-ecf13118f321
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

--- 

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongo-claim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: ebs-sc
#  resources:
#    requests:
#      storage: 4Gi